# Generated by Django 4.1.4 on 2022-12-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
