# Generated by Django 4.1.4 on 2022-12-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0002_user_is_admin_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(blank=True, max_length=150, verbose_name="Title"),
                ),
                (
                    "Body",
                    models.CharField(blank=True, max_length=150, verbose_name="Body"),
                ),
            ],
        ),
    ]
