# Generated by Django 4.1.4 on 2022-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0004_rename_notifications_notification"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="Body",),
        migrations.RemoveField(model_name="notification", name="Title",),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
